In [5]:
# GRADED FUNCTION: basic_sigmoid
import math
### START CODE HERE ###
def sigmoid(x):
    a = 1.0 / (1 + math.exp(-x))
    return a

s = sigmoid(2.2)
print(s)
### END CODE HERE ###

0.9002495108803148


In [6]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


In [7]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


In [8]:
# GRADED FUNCTION: sigmoid

import numpy as np # this means you can access numpy functions by writing np.function() instead of numpy.function()

def sigmoid_np(x):
    s = 1.0 / (1 + np.exp(x))
    return(s)

In [9]:
x = np.array([1, 2, 3])
sigmoid_np(x)

array([0.26894142, 0.11920292, 0.04742587])

In [10]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    s = sigmoid_np(x)
    return s*(1-s)

In [11]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


In [16]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    return v


In [17]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [18]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    x_norm = np.linalg.norm(x,axis = 1,keepdims = True)
    x_normalized = x/x_norm
    return x_normalized



In [19]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [27]:
# GRADED FUNCTION: softmax

def softmax(x):
    
    e = np.exp(x)
    e_sum = np.sum(e,axis=1,keepdims=True)# 按行相加，并且保持其二维特性-keepdims
    x_softmax = e / e_sum

    return(x_softmax)

In [28]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [29]:
# GRADED FUNCTION: L1

def L1(yhat, y):

    L = np.sum(np.abs(y-yhat))
    return L

In [30]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [35]:
# GRADED FUNCTION: L2

def L2(yhat, y):

    x = y-yhat
    L = np.dot(x,x)  # np.multiply()和* 操作符（相当于Matlab / Octave中的 .*）执行逐元素的乘法

    return L

In [36]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
