In [1]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,125.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 125.   99.    0.9]]


In [2]:
cal = A.sum(axis=0)  # 矩阵行相加 =1是列相加
print(cal)

[ 59.  229.  155.4  76.9]


In [4]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 45.41484716 33.46203346 10.40312094]
 [ 3.05084746 54.58515284 63.70656371  1.17035111]]


In [19]:
a = np.random.randn(5)

a = a.reshape(5,1)

assert(a.shape == (5,1))

      # 断言，判断表达式是否正确,false触发异常

In [5]:
import numpy as np
a = np.random.randn(4, 3)
b = np.random.randn(3, 2)
print(np.dot(a,b))

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 